### ISSUE TITLE
[JOSS REVIEW] Add Contributing Guide

### ISSUE THREAD

**Issue by finsberg** [florisvanvugt/biobabel#2]
As listed in the [Review Checklist](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines) there should be a Contributing Guide. This is typically done by adding a `CONTRIBUTING.md` (see https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors for more info)

This is related to https://github.com/openjournals/joss-reviews/issues/6884

**Comment by florisvanvugt** [comment]
Thank you for the suggestion. A contributing guide is now included. https://github.com/florisvanvugt/biobabel/commit/29e37805dbdcdf244a90d76d2763c068d5152bd4
