### ISSUE TITLE
[JOSS REVIEW] Missing dependency `neurokit2`

### ISSUE THREAD

**Issue by finsberg** [florisvanvugt/biobabel#4]
I tried to install and run the examples in the `tests` folder, and it looks like I am missing a dependency called `neurokit2`. If this is a  dependency that is only required to run the examples you could for examples add it as an optional dependency in the `pyproject.toml` (similar to what you have done with `pybdf`).

This is related to https://github.com/openjournals/joss-reviews/issues/6884#issuecomment-2167113578

**Comment by florisvanvugt** [comment]
Thank you for spotting that. Indeed, `neurokit2` is not required for the functionality of the package, but it is referred to for illustration purposes in the example usage script. I have followed your suggestion and marked it as an optional dependency.
https://github.com/florisvanvugt/biobabel/commit/78a788c3d77402440f12f527235fc2d6513a3a97
